---
title: "ENB enrichment"
output:
  html_document:
    fig_caption: yes
    df_print: paged
    code_folding: hide
 # bookdown::html_document2: default
  pdf_document:
    latex_engine: xelatex
    fig_caption: true
editor_options:
  chunk_output_type: console
delete_merged_file: true
---


```{r setup2, warning=FALSE,results='hide', echo=F,include=F}
library(here)
source(here("/code/0_functions/0_libraries.R"))

```

```{r}
people <- fread("data/publish/tidy_ENB/data/ENB_people.tsv")

```



```{r}


ENB_authors_split[,decade:=floor(aeg/10)*10]
plotdata2 <- ENB_authors_split[aeg!=1940][,.(books=uniqueN(RRid),authors=uniqueN(author_det)),.(year=aeg)][,authors_per_book:=authors/books]

plotdata2 %>% 
  ggplot()+
  geom_line(aes(x=year,y=authors_per_book)) +
  theme_bw()+
  #labs(x="Aasta",y="N",title="Eestikeelsed raamatud ja eestlasted")+
  labs(x="",y="N",title="Authors per publication)")+
  guides(color=F)



plotdata3 <- ENB_authors_split[aeg!=1940][,.(books=uniqueN(RRid),authors=uniqueN(author_det)),.(year=decade,author_det)][,authors_per_book:=books/authors]
plotdata3[order(-books),rank:=seq_len(.N),year][,booksfrommax:=books/max(books),year]

plotdata3 %>% 
  ggplot()+
  geom_line(aes(x=rank,y=books,color=year)) +
  theme_bw()+
  facet_wrap(~year)+
  #labs(x="Aasta",y="N",title="Eestikeelsed raamatud ja eestlasted")+
  labs(x="",y="N",title="Books in Estonian and Estonians (1800-1940)")+
  guides(color=F)



# uute autorite hulk kuidagi lisada
plotdata4 <- ENB_authors_split[aeg!=1940][,.(books=uniqueN(RRid),authors=uniqueN(author_det)),.(year=decade,RRid)]#[,.(authors=mean(authors)),.(year)]
plotdata4[order(-books),rank:=seq_len(.N),year][,booksfrommax:=books/max(books),year]

plotdata4 %>% 
  ggplot()+
  geom_line(aes(x=rank,y=books,color=year)) +
  theme_bw()+
  facet_wrap(~year)+
  #labs(x="Aasta",y="N",title="Eestikeelsed raamatud ja eestlasted")+
  labs(x="",y="N",title="Books in Estonian and Estonians (1800-1940)")+
  guides(color=F)


# uute autorite hulk kuidagi lisada
plotdata5 <- ENB_authors_split[aeg!=1940][,exists:=1][,firstbook:=cumsum(exists),author_det][firstbook==1][,.(firstauthors=.N),.(year=aeg)]
#plotdata5[order(-books),rank:=seq_len(.N),year][,booksfrommax:=books/max(books),year]

plotdata5 %>% 
  ggplot()+
  geom_line(aes(x=year+10,y=firstauthors)) +
  geom_point(aes(x=year+10,y=firstauthors)) +
  theme_bw()+
  #labs(x="Aasta",y="N",title="Eestikeelsed raamatud ja eestlasted")+
  labs(x="",y="N",title="New authors per decade (1800-1940)")+
  guides(color=F)


#book does not have just 1 author
plotdata6 <- ENB_authors_split[aeg!=1940][,firstbook_year:=min(aeg),author_det][,earliestauthor_year:=min(firstbook_year),RRid][,.(earliest_author=uniqueN(RRid)),.(year=aeg,earliestauthor_year)][order(earliestauthor_year)]
plotdata6 <- ENB_authors_split[aeg!=1940][,firstbook_year:=min(aeg),author_det][,earliestauthor_year:=min(firstbook_year),RRid][,.(earliest_author=uniqueN(RRid)),.(year=floor(aeg/5)*5,earliestauthor_year=floor(earliestauthor_year/5)*5)][order(earliestauthor_year)]

plotdata6 %>% 
  ggplot()+
  geom_col(aes(x=year,y=earliest_author,fill=factor(earliestauthor_year))) +#position="fill",# fct_rev(factor())
  #geom_point(aes(x=year+10,y=authors)) +
  theme_bw()+
  scale_fill_grey()+
  #labs(x="Aasta",y="N",title="Eestikeelsed raamatud ja eestlasted")+
  labs(x="",y="N",title="New authors per decade (1800-1940)")+
  guides(color=F)

ENB_authors_split[aeg!=1940][,.N,RRid][,.(NN=.N),N][order(N)]
ENB_authors_split[aeg!=1940][]


plotdata7 <- ENB_authors_split[aeg!=1940][,firstbook_year:=min(aeg),author_det][,earliestauthor_year:=max(firstbook_year),RRid][,.(earliest_author=uniqueN(RRid)),.(year=aeg,earliestauthor_year=earliestauthor_year)][order(earliestauthor_year)][,rel_start:=earliestauthor_year-year][rel_start<1&rel_start>-11,rel_start1:=-10][rel_start< -10&rel_start>-21,rel_start1:=-20][rel_start< -20&rel_start>-31,rel_start1:=-30][rel_start< -30,rel_start1:=-50]

plotdata7 %>% 
  ggplot()+
  geom_col(aes(x=year,y=earliest_author,fill=fct_rev(factor(rel_start1)))) +#position="fill",
  #geom_point(aes(x=year+10,y=authors)) +
  theme_bw()+
  scale_fill_grey()+
  #labs(x="Aasta",y="N",title="Eestikeelsed raamatud ja eestlasted")+
  labs(x="",y="N",title="New authors per decade (1800-1940)")+
  guides(color=F)

#midagi nadega
plotdata7.1 <- ENB_authors_split[aeg!=1940][,firstbook_year:=min(aeg),author_det][,earliestauthor_year:=max(firstbook_year),RRid][,.(earliest_author=uniqueN(RRid)),.(year=decade,earliestauthor_year=earliestauthor_year)][order(earliestauthor_year)][,rel_start:=earliestauthor_year-year][rel_start<1&rel_start>-11,rel_start1:=-10][rel_start< -10&rel_start>-21,rel_start1:=-20][rel_start< -20&rel_start>-31,rel_start1:=-30][rel_start< -30,rel_start1:=-50]

#midagi valet on arvutuses.
plotdata7.1 %>% 
  ggplot()+
  geom_col(aes(x=year,y=earliest_author,fill=fct_rev(factor(rel_start1)))) +#position="fill",
  #geom_point(aes(x=year+10,y=authors)) +
  theme_bw()+
  scale_fill_grey()+
  #labs(x="Aasta",y="N",title="Eestikeelsed raamatud ja eestlasted")+
  labs(x="",y="N",title="New authors per decade (1800-1940)")+
  guides(color=F)




plotdata7 %>% 
  ggplot()+
  geom_col(position="fill",aes(x=year,y=earliest_author,fill=fct_rev(factor(rel_start1)))) +#
  #geom_point(aes(x=year+10,y=authors)) +
  theme_bw()+
  scale_fill_grey()+
  #labs(x="Aasta",y="N",title="Eestikeelsed raamatud ja eestlasted")+
  labs(x="",y="N",title="New authors per decade (1800-1940)")+
  guides(color=F)
#new authors per population.

# ja siit peale asukohainfo, kas saab sellega midagi teha.

# siis vb asukohainfo + kubermangud.


# ja siis kubermangud ja see teine asukohainfo...





# Exclude simple character combinations that couldn't be identified
author_list <- unique(ENB_authors_split[,.(name,date,coauthor)][nchar(name)>7])

unique(ENB_authors_split[,.(name,date,coauthor)][nchar(name)<7])

```


```{r}

# can deal with the demographics stuff later.

demo1 <- fread(here("data/raw/demography/demography_earlier years2.csv"), skip=0, header=T)
demo1 <- demo1[!V1=="WRONGNA"][!V1=="NoRefWikiEst"]

#demo1[,.(V3,V5,V6,V7,V8,Eestlased)][V3=="",V3:=NA][,V3:=na.locf(V3)][V6=="Area"][V5%in%c("Estland_total","Estland_cities","Estland_county","Livland_cities","Livland_total","Livland_county")]
#places_simple<-unique(demo1[,.(Place,Type)])
#cj_grid <- CJ.table.1(places_simple,together)
#for some reason can't use key in this case.
#cj_grid <- CJ.table.2(places_simple,twomeasures[!is.na(saldo2)])
#demo_interpolate <- merge(cj_grid, demo_simple, by.x=c("year","Place","Type"),by.y=c("Time","Place","Type"),all=T)

known1 <- data.table(year=c(1796),pop1=c(257271+183799))
known2 <- data.table(year=c(1897),pop2=c(867794))
wholepop <- merge(twomeasures,known1,by="year",all=T)
wholepop <- merge(wholepop,known2,by="year",all=T)
(257271+183799)*cumprod(wholepop[year%in%c(1796:1897),rate2])
allpop <- data.table(year=1796:1897,pop=rev(867794/cumprod(rev(wholepop[year%in%c(1796:1897),rate2]))))
allpop2 <- data.table(year=1898:1935,pop=867794*cumprod(wholepop[year%in%c(1898:1934),rate2]))

totalpop_p <- save1[year< 1930&year>1799] %>% 
  ggplot(aes(x=year,y=pop))+
  geom_line()+
  theme_bw()+
  #labs(x="Aasta",y="N",title="Eestlasi 19. sajandil")
  labs(x="",y="N",title="Native Estonians (1800-1940)")
#ggsave(here("iive_sum_combined.png"),gridExtra::grid.arrange(birthrates_p,totalpop_p,ncol=2),width=8,height=4)
ggsave(here("iive_p2.png"),totalpop_p,width=4,height=4)
ggsave(here("pop_ests.png"),totalpop_p,width=4,height=4)

save1 <- rbind(allpop,allpop2)[,type:="pop"]
save2 <- works[aeg< 1941&aeg>1799][set=="eesti"][,.(pop=.N),.(year=aeg)][,type:="bib"]
save3 <- ENB_authors_split[,.(pop=.N),.(year=aeg)][,type:="author"]

both <- dcast(rbind(save1,save2,save3),year~type,value.var = "pop")
both[,bibpop:=bib/pop]
both[,autpop:=author/pop]
options(scipen=999)
bibs_p1 <- rbind(save1,save2)[type=="pop",type:="Native Estonians"][type=="bib",type:="Publications in Estonian"]%>% 
  ggplot(aes(x=year,y=pop,color=type))+
  geom_line() +
  facet_wrap(~type,scales="free_y")+
  theme_bw()+
  #labs(x="Aasta",y="N",title="Eestikeelsed raamatud ja eestlasted")+
  labs(x="",y="N",title="Books in Estonian and Estonians (1800-1940)")+
  guides(color=F)

ggsave(here("bibs_p1_eng.png"),bibs_p1,width=8,height=4)


#number of active authors (not counting reprints)
ENB_authors_split[,.(div=.N),.(year=aeg)]%>% 
  ggplot(aes(x=year,y=div))+
  geom_line()

both%>% 
  ggplot(aes(x=year,y=bibpop))+
  geom_line()# +
  #facet_wrap(~type,scales="free_y")

both%>% 
  ggplot(aes(x=year,y=autpop))+
  geom_line()# +


bibaut_perpop <- melt(both,id.var="year",measure.vars=c("bibpop","autpop"))[variable=="autpop",variable:="Authors per native speaker"][variable=="bibpop",variable:="Publications per native speaker"]%>% 
  ggplot(aes(x=year,y=value,color=variable))+
  geom_line() +
  facet_wrap(~variable,scales="free_y")+
  theme_bw()+
  #labs(x="aasta",y="N",title="Raamatuid ja aktiivset kirjarahvast inimese kohta")+
  labs(x="",y="",title="Publications and authors per Estonian native speaker (1800-1940)")+
  guides(color=F)

ggsave(here("bibaut_perpop_eng.png"),bibaut_perpop,width=8,height=4)

bibaut_perpop2 <- melt(both,id.var="year",measure.vars=c("bibpop","autpop"))[variable=="autpop"] %>% #[variable=="autpop",variable:="Authors per native speaker"][variable=="bibpop",variable:="Publications per native speaker"]%>% 
  ggplot(aes(x=year,y=value*1000000,color=variable))+
  geom_line() +
 # facet_wrap(~variable,scales="free_y")+
  theme_bw()+
  #labs(x="aasta",y="N",title="Raamatuid ja aktiivset kirjarahvast inimese kohta")+
  labs(x="",y="",title="Authors per 1M native speakers")+
  guides(color=F)
bibaut_perpop2

ggsave(here("bibaut_perpop_eng2.png"),bibaut_perpop2,width=4,height=4)


works[aeg< 2020&aeg>1800] %>%
  ggplot(aes(x=aeg,fill=set))+geom_histogram(binwidth=1)+
  theme_bw()+
  scale_fill_manual(values=cbPalette)

```



```{r linked persons gis birthplaces}

#authors enriched
#events_sf <- authors_enriched[!is.na(locbirth)&locbirth!=""][,lon:=] %>%
  #now adding jitter here too, might be a bit more in fact in these coordinates mb
  #mutate(lon2_jit=lon+rnorm,lat2_jit=lat+rnorm2)  %>%
#  st_as_sf(coords = "locbirth", crs = 4326)



#first simple check, but this will neglect a bunch of isiks!
forplot <- see[!duplicated(viaf)][,rnorm:=rnorm(1,0)/10,by=.(coauthor)][,rnorm2:=rnorm(1,0)/10,by=.(coauthor)] #taking just the first one removes 1/3 of dataset

forplot[,decade:=floor(birthyear/10)*10]
#forplot[episode=="synd"]
#forplot[,birthyear:=min(year),by=ISIK.id]
#forplot[,age:=year-birthyear]

#now 1268 names here
#forplot[!is.na(lat9)]

events_sf <- forplot[!is.na(lat9)][birthyear>1780][lat9>57.5][lat9<60][lon9>21.8][lon9<28.3][,.(birthyear=birthyear:(birthyear+20)),by=.(coauthor,lat9,lon9,date_simple,rnorm,rnorm2)] %>%
  #now adding jitter here too, might be a bit more in fact in these coordinates mb
  mutate(lon2_jit=lon9+rnorm,lat2_jit=lat9+rnorm2)  %>%
  st_as_sf(coords = c("lon2_jit", "lat2_jit"), crs = 4326)


#run initialize geography in 7.5_collect metainfo

#events_sf <- seebirths_m[!is.na(lat)][birthyear<1860] %>%
#  st_as_sf(coords = c("lon", "lat"), crs = 4326)


nc3 <- st_transform(nc2, 4326) %>% 
  st_transform(., '+proj=longlat +ellps=GRS80 +no_defs')# %>%
# since you want the centroids in a second geometry col:
#st_geometry()

#st_crs(nc3)
events_nc3 <- st_transform(events_sf, 4326) %>% 
  st_transform(., '+proj=longlat +ellps=GRS80 +no_defs')# %>%

res <- st_join(events_nc3, nc3)
#res <- st_intersects(events_nc3, nc3)

# unique(data.table(events_sf)[,.(coauthor,date_simple,lat9,lon9)])
# 700 names with locations. 825 with added names from VEPER locations
#each with 20 year point on it

#töötab küll, võttis mingi 5 min aega jooksutada...
#nc2$centroid <- st_centroid(nc2)
#install_version("plotly", version = "4.7.1", repos = "http://cran.us.r-project.org")
#install_version("plotly", version = "4.8", repos = "http://cran.us.r-project.org")
p <- ggplot() +
  geom_sf(data=nc3, color=alpha("grey",0.5), fill=alpha("blue",0.01)) +
  #geom_sf(data=events_sf) +
  #geom_sf(data=res,aes(text=paste("<br>","<br>",MAAKOND),frame=decade,id=coauthor),color="red",size=1.5,alpha=0.5) +
  geom_sf(data=res,aes(text=paste("<br>","<br>",MAAKOND),frame=birthyear,ids=geometry),color="red",size=1.0,alpha=0.5) +
  #scale_fill_distiller("Area", palette = "Greens") +
  ggtitle("Birthplaces of associated people") +
  coord_fixed(ratio=3.5/2)+
  theme_bw()


ggplotly(p) %>% animation_opts(frame = 300,
                             easing = "linear",
                             redraw = FALSE)


#just plot coords with lines, and check for long ones


```

